
const financialRecords = [ 
  // --- PEMASUKAN DANA (10 ITEMS) ---
  {
    customId: "INC-010626-001",
    date: "2026-06-01",
    type: "IN",
    flowType: "IN",
    amount: 5631302,
    paymentMethod: "TRANSFER",
    category: "SALDO TERKAHIR PT",
    description: "SISA SALDO BULAN MEI",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-01T08:00:00").getTime()
  },
  {
    customId: "INC-030526-001", // Match OCR ID precisely
    date: "2026-06-03",
    type: "IN",
    flowType: "IN",
    amount: 11750000,
    paymentMethod: "TRANSFER",
    category: "TERMIN KLIEN",
    description: "PEMBAYARAN FILTER SOFTENER DP 50%",
    sumberDana: "PT.TTI",
    refPiutang: "PTG-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T09:30:00").getTime()
  },
  {
    customId: "INC-060626-001",
    date: "2026-06-06",
    type: "IN",
    flowType: "IN",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    category: "HUTANG",
    description: "UANG MASUK TALANGAN DARI OWNER UNTUK GAJI KARYAWAN",
    sumberDana: "OWNER PT",
    refHutang: "HTG-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T10:00:00").getTime()
  },
  {
    customId: "INC-080626-001",
    date: "2026-06-08",
    type: "IN",
    flowType: "IN",
    amount: 50000000,
    paymentMethod: "TRANSFER",
    category: "TERMIN 1",
    description: "TANDA EQUIPMENT STP",
    sumberDana: "-",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-08T11:00:00").getTime()
  },
  {
    customId: "INC-100626-001",
    date: "2026-06-10",
    type: "IN",
    flowType: "IN",
    amount: 10000000,
    paymentMethod: "TRANSFER",
    category: "PEMBAYARAN KASBON",
    description: "UANG KASBON YANG DI BAYAR OWNER",
    sumberDana: "OWNER",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-10T09:00:00").getTime()
  },
  {
    customId: "INC-100626-002",
    date: "2026-06-10",
    type: "IN",
    flowType: "IN",
    amount: 11750000,
    paymentMethod: "TRANSFER",
    category: "TERMIN KLIEN",
    description: "PELUNASAN FILTER SOFTENER 50%",
    sumberDana: "KLIEN",
    refPiutang: "PTG-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-10T14:30:00").getTime()
  },
  {
    customId: "INC-120626-001",
    date: "2026-06-12",
    type: "IN",
    flowType: "IN",
    amount: 50000000,
    paymentMethod: "TRANSFER",
    category: "TERMIN",
    description: "TERMIN 100% - PARSIAL 1",
    sumberDana: "KLIEN",
    referenceId: "UEU TB SIMATUPANG",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T10:00:00").getTime()
  },
  {
    customId: "INC-200626-001",
    date: "2026-06-20",
    type: "IN",
    flowType: "IN",
    amount: 20000000,
    paymentMethod: "TRANSFER",
    category: "UANG MASUK",
    description: "PEMBAYARAN UANG KASBON",
    sumberDana: "MUHAMMAD YASIN",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T11:00:00").getTime()
  },
  {
    customId: "INC-230626-001",
    date: "2026-06-23",
    type: "IN",
    flowType: "IN",
    amount: 113220000,
    paymentMethod: "TRANSFER",
    category: "TERMIN",
    description: "TERMIN PROGRES 20%",
    sumberDana: "PT. TEI",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-23T10:00:00").getTime()
  },
  {
    customId: "INC-260626-001",
    date: "2026-06-26",
    type: "IN",
    flowType: "IN",
    amount: 11753500,
    paymentMethod: "TRANSFER",
    category: "PEMBAYARAN",
    description: "PEMBAYARAN PEMELIHARAAN IPAL PKM SINDANG JAYA",
    sumberDana: "PUSKESMAS SINDANG JAYA",
    referenceId: "PKM SINDANGN JAYA",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T09:30:00").getTime()
  },

  // --- PENGELUARAN REKENING BANK PT (44 ITEMS) ---
  {
    customId: "BNK-010626-001",
    date: "2026-06-01",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 160000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "OPERASIONAL KEBUTUHAN PERUSAHAAN",
    rekPenerima: "FAISAL",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-01T10:00:00").getTime()
  },
  {
    customId: "BNK-030626-001",
    date: "2026-06-03",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 300000,
    paymentMethod: "TRANSFER",
    category: "OPERASIONAL",
    description: "OPERASIONAL MEETING KARAWANG JIDAN DAN BANG YASIN",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T11:00:00").getTime()
  },
  {
    customId: "BNK-030626-002",
    date: "2026-06-03",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 500000,
    paymentMethod: "TRANSFER",
    category: "KASBON",
    description: "KASBON TIM PROJECT WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T14:00:00").getTime()
  },
  {
    customId: "BNK-040626-001",
    date: "2026-06-04",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 400000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "KEBUTUHAN PERUSAHAAN",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-04T10:00:00").getTime()
  },
  {
    customId: "BNK-050626-001",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 8300000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN FILTER SOFTENER FRP DAN MEDIA FILTER",
    rekPenerima: "ANDRIY SE - SUPPLIER",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T09:30:00").getTime()
  },
  {
    customId: "BNK-050626-002",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 5000000,
    paymentMethod: "TRANSFER",
    category: "GAJI",
    description: "GAJI BULAN MEI FAISAL",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T13:00:00").getTime()
  },
  {
    customId: "BNK-050626-003",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 500000,
    paymentMethod: "TRANSFER",
    category: "TARIK CASH",
    description: "TARIK CASH DI ATM",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T15:00:00").getTime()
  },
  {
    customId: "BNK-060626-001",
    date: "2026-06-06",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2800000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "GAJI TIM PROJECT WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T11:00:00").getTime()
  },
  {
    customId: "BNK-080626-001",
    date: "2026-06-08",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 30000000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "DP POMPA",
    rekPenerima: "WINGGI APRIYANTO",
    sumberDana: "REKENING PT",
    refHutang: "HTG-010",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-08T10:00:00").getTime()
  },
  {
    customId: "BNK-090626-001",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2000000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "OPERASIONAL PROJECT WESTMARK DAN KANTOR",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T09:00:00").getTime()
  },
  {
    customId: "BNK-090626-002",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 10000000,
    paymentMethod: "TRANSFER",
    category: "KASBON",
    description: "KASBON BANG YASIN",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T11:00:00").getTime()
  },
  {
    customId: "BNK-090626-003",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 4100000,
    paymentMethod: "TRANSFER",
    category: "GAJI",
    description: "GAJI JIDAN BULAN MEI DAN CLAIM ERUL 600 RIBU",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T14:30:00").getTime()
  },
  {
    customId: "BNK-120626-001",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 3237000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "KASBON TIM WELI 500, PANJUL 500, IKA 1 JUTADAN REIMBURSE JIDAN",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T09:30:00").getTime()
  },
  {
    customId: "BNK-120626-002",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2000000,
    paymentMethod: "TRANSFER",
    category: "GAJI",
    description: "GAJI FINANCE",
    rekPenerima: "JIMMI PARULIAN HUTABARAT",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T13:00:00").getTime()
  },
  {
    customId: "BNK-130626-001",
    date: "2026-06-13",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 10750000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN POMPA GRUNDFOS NS30-18 1 UNIT",
    rekPenerima: "FEBRIAN PERMANA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-13T09:00:00").getTime()
  },
  {
    customId: "BNK-130626-002",
    date: "2026-06-13",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 5000000,
    paymentMethod: "TRANSFER",
    category: "FEE",
    description: "PEMBAYARAN DP KE 2 DESAIN",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-13T11:00:00").getTime()
  },
  {
    customId: "BNK-130626-003",
    date: "2026-06-13",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 760100,
    paymentMethod: "TRANSFER",
    category: "OPERASIONAL",
    description: "MAKAN SIANG MEETING PROJECT BARU - WARUNG SUNDA",
    rekPenerima: "WARUNG SUNDA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-13T13:30:00").getTime()
  },
  {
    customId: "BNK-140626-001",
    date: "2026-06-14",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 6522000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "FEE KANG RAHMAT, BAYAR KONTRAKA WESTMARK, OPERASIONAL KUJUNGAN PROJECT WESTMARK DAN SIMATUPANG",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-14T10:00:00").getTime()
  },
  {
    customId: "BNK-150626-001",
    date: "2026-06-15",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 16000000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "BELANJA KEBUTUHAN PROJECT WESTMARK VALVE KITZ DAN JET STEAMER BARU",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-15T09:30:00").getTime()
  },
  {
    customId: "BNK-150626-002",
    date: "2026-06-15",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "BELANJA KEKURANGAN VALVE KITZ PROJEC WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-15T11:30:00").getTime()
  },
  {
    customId: "BNK-150626-003",
    date: "2026-06-15",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 20000000,
    paymentMethod: "TRANSFER",
    category: "KASBON",
    description: "KASBON BANG YASIN",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-15T14:00:00").getTime()
  },
  {
    customId: "BNK-150626-004",
    date: "2026-06-15",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2684000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "BELANJA EQUIPMENT PVC WESTMARK",
    rekPenerima: "TERMINAL KARYA CIPTA EMA",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-15T16:00:00").getTime()
  },
  {
    customId: "BNK-180626-001", // This is customId for 17/06, matching original log table precisely
    date: "2026-06-17",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1330000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN EQUIPMENT WESTMARK - UND 80 DAN BESI SIKU",
    rekPenerima: "HELEN KURNIAWAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-17T09:30:00").getTime()
  },
  {
    customId: "BNK-170626-002",
    date: "2026-06-17",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 5338000,
    paymentMethod: "TRANSFER",
    category: "BIAYA JASA",
    description: "SEDOT TINJA PAL JAYA",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-17T11:00:00").getTime()
  },
  {
    customId: "BNK-180626-001-B", // Avoid key collision for duplicated BNK-180626-001, we use unique doc ID
    date: "2026-06-18",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 401000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN EQUIPMENT WESTMARK PIPA BESI, FLANGE DAN SDD",
    rekPenerima: "SINAR VALCOSINDO TEKNIK",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-18T10:00:00").getTime()
  },
  {
    customId: "BNK-180626-002",
    date: "2026-06-18",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 428349,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN TANG LAS, METERAN, KAWAT LAS PROJEK WESTMARK",
    rekPenerima: "ASIA JAYA PARAMA",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-18T14:00:00").getTime()
  },
  {
    customId: "BNK-200626-001",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 6819000,
    paymentMethod: "TRANSFER",
    category: "GAJI",
    description: "Gaji Tim Teknisi Project Westmark, Claim Faisal 425k, Bayar Wifi Indihome 409k",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T09:30:00").getTime()
  },
  {
    customId: "BNK-220626-001",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 4711000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "BELANJA KEBUTUHAN PROJECT WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T09:00:00").getTime()
  },
  {
    customId: "BNK-220626-002",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 5000000,
    paymentMethod: "TRANSFER",
    category: "KASBON",
    description: "KASBON BANG YASIN",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T11:00:00").getTime()
  },
  {
    customId: "BNK-220626-003",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "BELANJA KEKURANGAN EQUIPMENT WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T14:30:00").getTime()
  },
  {
    customId: "BNK-240626-001",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 4250000,
    paymentMethod: "TRANSFER",
    category: "FEE",
    description: "PEMBAYARAN FEE DESAIN CAD PROYEK UEU TB SIMATUPANG",
    rekPenerima: "SOLEHUDIN DRAFTER",
    sumberDana: "REKENING PT",
    referenceId: "ESA UNGGUL SIMATUPANG",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T09:30:00").getTime()
  },
  {
    customId: "BNK-240626-002",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2863800,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PELUNASAN 10% EXHAUST FAN",
    rekPenerima: "IRWAN HERMAWAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T11:00:00").getTime()
  },
  {
    customId: "BNK-240626-003",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 700000,
    paymentMethod: "TRANSFER",
    category: "BIAYA JASA",
    description: "DP JASA KALIBRASI WATER METER",
    rekPenerima: "GUNUNG LE SIRAIT",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T14:00:00").getTime()
  },
  {
    customId: "BNK-240626-004",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 12000000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH",
    description: "BELANJA KEBUTUHAN WESTMARK DAN KEBUTUHAN KANTOR",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T16:00:00").getTime()
  },
  {
    customId: "BNK-250626-001",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 25000000,
    paymentMethod: "TRANSFER",
    category: "HUTANG",
    description: "CICILAN PEMBAYARAN DANA OWNER",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T09:00:00").getTime()
  },
  {
    customId: "BNK-250626-002",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 8875000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "Pembelian 1 Unit Pompa LMI PD063 dan & 7 pcs Pressure Gague 10 Bar 2,5\" + Vlok ring 1/4\"x1/2\"",
    rekPenerima: "A LILI HARIRI",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T11:00:00").getTime()
  },
  {
    customId: "BNK-250626-003",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 3000000,
    paymentMethod: "TRANSFER",
    category: "PATTYCASH PROYEK",
    description: "BELANJA KEBUTUHAN PROYEK WESTMARK",
    rekPenerima: "JIDAN RAMADHAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T14:00:00").getTime()
  },
  {
    customId: "BNK-250626-004",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 700000,
    paymentMethod: "TRANSFER",
    category: "BIAYA JASA",
    description: "PELUNASAN KALIBRASI WATER METER",
    rekPenerima: "GUNUNG LEO SIRAIT",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T15:00:00").getTime()
  },
  {
    customId: "BNK-250626-005",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1050000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN TOREN AIR 300 LITER PENGUIN",
    rekPenerima: "VENIA INTI CEMERLANG CV",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T16:00:00").getTime()
  },
  {
    customId: "BNK-260626-001",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2800000,
    paymentMethod: "TRANSFER",
    category: "BIAYA JASA",
    description: "PEMBAYARAN JASA NOTARIS DOKUMEN GARDA",
    rekPenerima: "PT LEGAL NUSANTARA INDONESI",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T09:30:00").getTime()
  },
  {
    customId: "BNK-260626-002",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1500000,
    paymentMethod: "TRANSFER",
    category: "KASBON",
    description: "KASBON KARYAWAN LAPANGAN WESTMARK",
    rekPenerima: "FAISAL MUSTOPA",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T11:00:00").getTime()
  },
  {
    customId: "BNK-260626-003",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 9753500,
    paymentMethod: "TRANSFER",
    category: "FEE",
    description: "FEE KANG WAWAN PKM SINDANG JAYA",
    rekPenerima: "AHMAD SUTAJIB",
    sumberDana: "REKENING PT",
    referenceId: "PKM SINDANG",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T13:00:00").getTime()
  },
  {
    customId: "BNK-260626-004",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 14268000,
    paymentMethod: "TRANSFER",
    category: "BELANJA",
    description: "PEMBELIAN QDC PROYEK WESTMARK",
    rekPenerima: "WINGGI APRIYANTO",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T15:00:00").getTime()
  },
  {
    customId: "BNK-260626-005",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 35000000,
    paymentMethod: "TRANSFER",
    category: "PAJAK",
    description: "PENYISIHAN DANA PAJAK",
    rekPenerima: "MUHAMMAD YASIN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T16:30:00").getTime()
  },

  // --- PENGELUARAN VIA REKENING PRIBADI / TALANGAN (65 ITEMS) ---
  {
    customId: "PRS-020626-001",
    date: "2026-06-02",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 122000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN PLASTIK POLYBAG",
    sumberDana: "REKENING PRIBADI",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-02T10:00:00").getTime()
  },
  {
    customId: "PRS-030526-001",
    date: "2026-06-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON TIM PANJUL 200, IKA 200, WELI 100 PROJECT WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-002",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T11:00:00").getTime()
  },
  {
    customId: "PRS-030626-001",
    date: "2026-06-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 77000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "MAKAN SIANG MCD",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T12:00:00").getTime()
  },
  {
    customId: "PRS-030626-002",
    date: "2026-06-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON TIM PROJECT WESTMARK, PANJUL 200, IKA 200, WELI 100",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-002",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-03T14:00:00").getTime()
  },
  {
    customId: "PRS-040626-001",
    date: "2026-06-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 240000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN TERPAL PROJECT WESTMARK 4X4 M",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-04T10:00:00").getTime()
  },
  {
    customId: "PRS-040626-002",
    date: "2026-06-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "TRANSFER",
    personalHolder: "WELI MAHESA",
    category: "KASBON",
    description: "KASBON WELI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-04T11:00:00").getTime()
  },
  {
    customId: "PRS-050626-001",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 137000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL",
    category: "OPERASIONAL KANTOR",
    description: "PEMBELIAN TISU SATU DUS",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T09:00:00").getTime()
  },
  {
    customId: "PRS-050626-002",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 92000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN RODA TROLEY",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T11:00:00").getTime()
  },
  {
    customId: "PRS-050626-003",
    date: "2026-06-05",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 192000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL PROJEK",
    description: "KONSUMSI MINUM LAPANG, PRINT DOKUMEN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-050626-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-05T14:30:00").getTime()
  },
  {
    customId: "PRS-060626-001",
    date: "2026-06-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 15000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "BELI BENSIN FAISAL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T09:00:00").getTime()
  },
  {
    customId: "PRS-060626-002",
    date: "2026-06-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 900000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "GAJI",
    description: "GAJI PANJUL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-060626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T10:00:00").getTime()
  },
  {
    customId: "PRS-060626-003",
    date: "2026-06-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 900000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "GAJI",
    description: "GAJI IKA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-060626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T11:00:00").getTime()
  },
  {
    customId: "PRS-060626-004",
    date: "2026-06-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "GAJI",
    description: "GAJI WELI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-060626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-06T12:00:00").getTime()
  },
  {
    customId: "PRS-070626-001",
    date: "2026-06-07",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    personalHolder: "BANG YASIN",
    category: "FEE",
    description: "PEMBAYARAN DP DESAIN",
    sumberDana: "REKENING PRIBADI",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-07T10:00:00").getTime()
  },
  {
    customId: "PRS-070626-002",
    date: "2026-06-07",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN KARUNG 50 PCS",
    sumberDana: "REKENING PRIBADI",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-07T11:00:00").getTime()
  },
  {
    customId: "PRS-090626-001",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 400000,
    paymentMethod: "TRANSFER",
    personalHolder: "BANG YASIN",
    category: "LOGISTIK",
    description: "ONGKIR FILTER SOFTENER",
    sumberDana: "REKENING PRIBADI",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T08:30:00").getTime()
  },
  {
    customId: "PRS-090626-002",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN EQUIPMENT PROJECT WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T10:00:00").getTime()
  },
  {
    customId: "PRS-090626-003",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 152500,
    paymentMethod: "CASH",
    personalHolder: "WELI MAHESA",
    category: "KASBON",
    description: "KASBON WELI MAHESA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T11:30:00").getTime()
  },
  {
    customId: "PRS-090626-004",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 200000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON PANJUL 100 DAN IKA 100",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T13:00:00").getTime()
  },
  {
    customId: "PRS-090626-005",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 31000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "PEMBELIAN TOKEN LISTRIK 50 RIBU",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T14:30:00").getTime()
  },
  {
    customId: "PRS-090626-006",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 20500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "PEMBELIAN TOKEN LISTRIK KONTRAKAN TAMAN ANGGREK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-030626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T15:30:00").getTime()
  },
  {
    customId: "PRS-090626-007",
    date: "2026-06-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 20500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "PEMBELIAN TOKEN LISTRIK KONTRAKAN TAMAN ANGGREK 50K",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-050626-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-09T16:30:00").getTime()
  },
  {
    customId: "PRS-100626-001",
    date: "2026-06-10",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 22000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL KANTOR",
    description: "PEMBELIAN GALON LE MINARLE",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-10T10:00:00").getTime()
  },
  {
    customId: "PRS-100626-002",
    date: "2026-06-10",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 200000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN MATA BOR DAN KARUNG",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-10T11:00:00").getTime()
  },
  {
    customId: "PRS-120626-001",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON IKA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-120626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T10:00:00").getTime()
  },
  {
    customId: "PRS-120626-002",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON PANJUL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-120626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T11:00:00").getTime()
  },
  {
    customId: "PRS-120626-003",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON WELI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-120626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T11:30:00").getTime()
  },
  {
    customId: "PRS-120626-004",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON JIDAN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T13:00:00").getTime()
  },
  {
    customId: "PRS-120626-005",
    date: "2026-06-12",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "OPERASIONAL JIDAN KE WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-12T14:30:00").getTime()
  },
  {
    customId: "PRS-130626-001",
    date: "2026-06-13",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 122000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "MAKAN MALAM SAMBAL RAMPAI - KUNJUNGAN PROJECT WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-140626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-13T18:00:00").getTime()
  },
  {
    customId: "PRS-130626-001-DUPL", // Handle duplicated key in OCR gracefully
    date: "2026-06-14",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 200000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "KASBON",
    description: "KASBON WELI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-14T09:00:00").getTime()
  },
  {
    customId: "PRS-140626-002",
    date: "2026-06-14",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 5000000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON KANG RAHMAT",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-140626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-14T11:00:00").getTime()
  },
  {
    customId: "PRS-140626-003",
    date: "2026-06-14",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1400000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL TIM",
    description: "PEMBAYARAN KONTRAKAN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-140626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-14T14:30:00").getTime()
  },
  {
    customId: "PRS-170626-001",
    date: "2026-06-17",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 45000,
    paymentMethod: "CASH",
    personalHolder: "OPERASIONAL KANTOR",
    category: "BELANJA",
    description: "PEMBELIAN KERTAS A4 1 RIM",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-17T10:00:00").getTime()
  },
  {
    customId: "PRS-180626-001",
    date: "2026-06-18",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "KASBON",
    description: "KASBON PANJUL 100",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-18T11:00:00").getTime()
  },
  {
    customId: "PRS-200626-001",
    date: "2026-06-19",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 25000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL MEETING",
    description: "BELI MINUMAN UNTUK MEETING BOGOR COVER ATM BRI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-090626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-19T10:00:00").getTime()
  },
  {
    customId: "PRS-190626-002",
    date: "2026-06-19",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 325000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "MAKAN MALAM MEETING BOGOR PROYEK COVER ATM BRI",
    sumberDana: "REKENING PRIBADI",
    refIdBank: "HTG-008",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-19T18:00:00").getTime()
  },
  {
    customId: "PRS-190626-003",
    date: "2026-06-19",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "OPERASIONAL JIDAN FAISAL MAKAN DAN BENSIN MEETING COVER ATM BRI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-19T21:00:00").getTime()
  },
  {
    customId: "PRS-200626-001-B",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1995000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "GAJI FAUZYAWAN/ PANJUL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T09:30:00").getTime()
  },
  {
    customId: "PRS-200626-002",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "KEKURANGAN GAJI FAUZYAWAN / PANJUL, (UANG FAISAL)",
    sumberDana: "REKENING PRIBADI",
    refIdBank: "HTG-009",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T11:00:00").getTime()
  },
  {
    customId: "PRS-200626-003",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1995000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "GAJI WELI MAHESA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T13:00:00").getTime()
  },
  {
    customId: "PRS-200626-004",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 409000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL KANTOR",
    description: "PEMBAYARAN TAGIHAN WIFI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T14:30:00").getTime()
  },
  {
    customId: "PRS-200926-001",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1995000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "GAJI IKA SUSANTO",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T16:00:00").getTime()
  },
  {
    customId: "PRS-200626-007",
    date: "2026-06-20",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 325000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL",
    category: "REIMBURSE",
    description: "MAKAN MALAM MEETING BOGOR",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-200626-001",
    refHutang: "HTG-008",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-20T18:00:00").getTime()
  },
  {
    customId: "PRS-220626-001",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 2075000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN BESI SIKU, THINER, CAT, ZINCROME - TOKO BESI TANGERANG",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-220626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T09:30:00").getTime()
  },
  {
    customId: "PRS-220626-002",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 2636000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMDHAN",
    category: "BELANJA",
    description: "GATE VALVE KITZ 1 1/2\" - 2PCS, 1\"- 3 PCS, 1/2\" - 3 PCS, ELBOW DRAT 1/2\" - PCS, FLANG PVC 5 PCS, UBOLT 10 PCS, DYNABOLT 100 PCS, REDUCER PVC 1 PCS - TECHVALVE INDO",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-220626-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T11:00:00").getTime()
  },
  {
    customId: "PRS-220626-003",
    date: "2026-06-22",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 74000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "GATE VALVE KITZ 1 1/2\" - 2PCS, 1\"- 3 PCS, 1/2\" - 3 PCS, ELBOW DRAT 1/2\" - PCS, FLANG PVC 5 PCS, UBOLT 10 PCS, DYNABOLT 100 PCS, REDUCER PVC 1 PCS - TECHVALVE INDO",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-220626-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-22T14:30:00").getTime()
  },
  {
    customId: "PRS-230626-001",
    date: "2026-06-23",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 55000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "JASA PENGIRIMAN",
    description: "BIAYA ONGKIR LALAMOVE KIRIM INVOICE KE PT TEI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-220626-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-23T11:00:00").getTime()
  },
  {
    customId: "PRS-240626-001",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 8009100,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "BELANJA KEBUTUHAN ELEKTRIKAL PROYEK WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T09:30:00").getTime()
  },
  {
    customId: "PRS-240626-002",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 639840,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "BELANJA KEBUTUHAN ELEKTRIKAL WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T11:00:00").getTime()
  },
  {
    customId: "PRS-240626-004",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "REIMBURSE",
    description: "CLAIM FAISAL MUSTOPA UNTUK KEKURANGAN GAJI PANJUL 500K",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    refHutang: "HTG-009",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T14:00:00").getTime()
  },
  {
    customId: "PRS-240626-004-B",
    date: "2026-06-24",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "PATTYCASH",
    description: "KASBON/PATTYCASH JIDAN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-24T16:00:00").getTime()
  },
  {
    customId: "PRS-250626-001",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 661400,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN FLOATING UNTUK PROYEK SAKATA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "SAKATA",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T09:30:00").getTime()
  },
  {
    customId: "PRS-250626-002",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 210000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN DURADUS DAN KABEL TIES",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-250626-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T11:00:00").getTime()
  },
  {
    customId: "PRS-250626-003",
    date: "2026-06-25",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 50000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL",
    description: "BELI BENSIN UNTUK BELANJA DAN NGANTER BARANG KE KEMIRI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-250626-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-25T14:00:00").getTime()
  },
  {
    customId: "PRS-260626-001",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON PANJUL 500",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-260626-002",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T09:30:00").getTime()
  },
  {
    customId: "PRS-260626-002",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "KASBON",
    description: "KASBON IKA 500K",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-260626-002",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T11:00:00").getTime()
  },
  {
    customId: "PRS-260626-003",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "KASBON",
    description: "KASBON WELI 500K",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-260626-002",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T11:30:00").getTime()
  },
  {
    customId: "PRS-260626-004",
    date: "2026-06-26",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 134500,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN EQUIPMENT KEBUTUHAN WESTMARK TOKO BANGUNAN SINAR MAS + ADMIN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-26T14:30:00").getTime()
  },
  {
    customId: "PRS-290626-001",
    date: "2026-06-29",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 50000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "BELANJA ATK UNTUK KANTOR",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-29T10:00:00").getTime()
  },
  {
    customId: "PRS-290626-002",
    date: "2026-06-29",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 152500,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "OPERASIONAL WELI VISIT KE PROYEK ES UNGGUL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "ESA UNGGU TB SIMATUPANG",
    recordedBy: "admin",
    timestamp: new Date("2026-06-29T14:30:00").getTime()
  },
  {
    customId: "PRS-300626-001",
    date: "2026-06-30",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 532000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN EQUIPMENT PROYEK WESTMARK DI TB SINAR TOMANG JAKARTA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-30T09:30:00").getTime()
  },
  {
    customId: "PRS-300626-002",
    date: "2026-06-30",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 357700,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN BOLT UNTUK PROYEK WESTMARK - SHOPEE JIDAN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-30T11:00:00").getTime()
  },
  {
    customId: "PRS-300626-003",
    date: "2026-06-30",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 46500,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN AQUA BOTOL 1 DUS UNTUK KANTOR",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-06-30T14:00:00").getTime()
  },
  {
    customId: "PRS-300626-004",
    date: "2026-06-30",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 350000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN RESIN DAN AQUA PROOF PROYEK WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-06-30T16:00:00").getTime()
  },
  // --- JULY 2026 RECORDS ---
  {
    customId: "BNK-010726-001",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2500000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "PATTYCASH",
    description: "PEMBAYARAN SKUM SKIMER DAN KASBON JIDAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T08:00:00").getTime()
  },
  {
    customId: "BNK-010726-002",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 279500,
    paymentMethod: "TRANSFER",
    personalHolder: "SINAR VALCOSINDO TEKN",
    category: "BELANJA",
    description: "PEMBELIAN FITTING PVC PROYEK WESTMARK",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T08:30:00").getTime()
  },
  {
    customId: "BNK-010726-003",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1000000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "PATTYCASH",
    description: "PEGANGAN DAN PATTYCASH KEBUTUHAN KANTOR",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T10:00:00").getTime()
  },
  {
    customId: "PRS-010726-001",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 220000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN RUPING DAN TAMBANG PROYEK WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T09:00:00").getTime()
  },
  {
    customId: "PRS-010726-002",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 34000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "UANG ROKOK PAK JOKO MEETING BOGOR COVER ATM BRI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T11:00:00").getTime()
  },
  {
    customId: "PRS-010726-003",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 99000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "MEETING CAFE PROYEK BOGOR COVER ATM BRI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T14:00:00").getTime()
  },
  {
    customId: "PRS-010726-004",
    date: "2026-07-01",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 179000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA",
    description: "PEMBELIAN COLOKAN LISTRIK DAN STOP KONTAK UNTUK PROYEK WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-01T16:30:00").getTime()
  },
  {
    customId: "PRS-020726-001",
    date: "2026-07-02",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 231000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "REIMBURSE",
    description: "CLAIM JIDAN OPERASIONAL TANGGAL 1 DAN 2 JULI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-02T10:00:00").getTime()
  },
  {
    customId: "BNK-020726-001",
    date: "2026-07-02",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1405000,
    paymentMethod: "TRANSFER",
    personalHolder: "HELEN KURNIAWAN",
    category: "BELANJA",
    description: "PEMBELIAN PIPA PIPA GALVANIS DAN THINNER 1 GALON",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-02T14:00:00").getTime()
  },
  {
    customId: "PRS-030726-001",
    date: "2026-07-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 100000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "ONGKOS BELANJA KEBUTUHAN WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-03T09:00:00").getTime()
  },
  {
    customId: "PRS-030726-002",
    date: "2026-07-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 70299,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "BELANJA KANTOR",
    description: "PEMBELIAN PULPEN 1 PACK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-03T11:30:00").getTime()
  },
  {
    customId: "PRS-030726-003",
    date: "2026-07-03",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 60000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "PEMBELIAN MARTABAK UNTUK JAMUAN INVESTOR DI KANTOR",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-010726-003",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-03T15:00:00").getTime()
  },
  {
    customId: "BNK-040726-001",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "KEKURANGAN GAJI TIM WESTMARK",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T10:30:00").getTime()
  },
  {
    customId: "PRS-040726-001",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 8500000,
    paymentMethod: "CASH",
    personalHolder: "MUHAMMAD YASIN",
    category: "GAJI",
    description: "GAJI FAISAL 5 JUTA DAN GAJI JIDAN 5",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-011",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T08:00:00").getTime()
  },
  {
    customId: "PRS-040726-002",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 6000000,
    paymentMethod: "CASH",
    personalHolder: "MUHAMMAD YASIN",
    category: "GAJI",
    description: "GAJI PANJUL 1.865, GAJI IKA 2.665, GAJI WELI 1.915",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-012",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T09:00:00").getTime()
  },
  {
    customId: "PRS-040726-003",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 445000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "KEKURANGAN GAJI TIM WESTMARK",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040726-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T10:00:00").getTime()
  },
  {
    customId: "PRS-040726-004",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 446500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA",
    description: "PEMBELIAN FITTING PVC WESTMARK",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-013",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T11:00:00").getTime()
  },
  {
    customId: "PRS-040726-005",
    date: "2026-07-04",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 12500000,
    paymentMethod: "CASH",
    personalHolder: "BANG YASIN",
    category: "BELANJA",
    description: "PEMBAYARAN PELUNASAN 50% PANEL CONTROL WESTMARK",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-017",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-04T12:00:00").getTime()
  },
  {
    customId: "PRS-060726-001",
    date: "2026-07-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 66000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA KANTOR",
    description: "PEMBELIAN MOUSE JIDA",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-240626-004",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-06T10:00:00").getTime()
  },
  {
    customId: "PRS-060726-002",
    date: "2026-07-06",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 55000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA KANTOR",
    description: "SISA PEMBAYARAN PEMBELIAN MOUSE JIDAN PAKAI",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-040726-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-06T11:30:00").getTime()
  },
  {
    customId: "PRS-070726-001",
    date: "2026-07-07",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL PROYEK",
    description: "DP KONTRAKAN",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-017",
    referenceId: "PKM KEBON JERUK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-07T10:00:00").getTime()
  },
  {
    customId: "PRS-080726-001",
    date: "2026-07-08",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 113000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "PEMBELIAN LEM, WD, DAN KNEE UNTUK WESTMARK",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-018",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-08T09:30:00").getTime()
  },
  {
    customId: "PRS-080726-002",
    date: "2026-07-08",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 265000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "PEMBELIAN U BOLT DAN DYNABOLT UNTUK WESTMARK + ONGKIR 15K",
    sumberDana: "REKENING PRIBADI",
    refHutang: "HTG-019",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-08T11:00:00").getTime()
  },
  {
    customId: "INC-080726-001",
    date: "2026-07-08",
    type: "IN",
    flowType: "IN",
    amount: 25000000,
    paymentMethod: "TRANSFER",
    category: "TERMIN",
    description: "TERMIN PEKERJAAN SELESAI PARSIAL 2",
    sumberDana: "REKENING PT",
    referenceId: "UEU TB SIMATUPANG",
    recordedBy: "admin",
    timestamp: new Date("2026-07-08T14:30:00").getTime()
  },
  {
    customId: "BNK-080726-001",
    date: "2026-07-08",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 850000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "JASA",
    description: "PEMBAYARAN SEDOT TINJA WESTMARK",
    sumberDana: "REKENING PT",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-08T16:00:00").getTime()
  },
  {
    customId: "BNK-080726-002",
    date: "2026-07-08",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 4000000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "PATTYCASH",
    description: "PATTYCASH UNTUK KEBUTUHAN KANTOR DAN PROYEK FAISAL",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-08T17:00:00").getTime()
  },
  {
    customId: "PRS-090726-001",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1000000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "OPERASIONAL PROYEK",
    description: "DP KONTRAKAN KEBON JERUK (CLAIM HUTANG ID HUTANG HTG-017 ALOKASI DANA DARI ID BANK BNK-080726-002)",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    refHutang: "HTG-017",
    referenceId: "PKM KEBON JERUK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T09:00:00").getTime()
  },
  {
    customId: "PRS-090726-002",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 113000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "CLAIM PEMBELIAN LEM, WD DAN KNEE WESTMARK (CLAIM HUTANG ID HUTANG HTG-018 ALOKASI DANA DARI ID BANK BNK-080726-002)",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    refHutang: "HTG-018",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T09:30:00").getTime()
  },
  {
    customId: "PRS-090726-003",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 265000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "CLAIM PEMBELIAN UBOLT DYNABOLT UNTUK WESTMARK + ONGKIR 15K (CLAIM HUTANG ID HUTANG HTG-019 ALOKASI DANA DARI ID BANK BNK-080726-002)",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    refHutang: "HTG-019",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T10:00:00").getTime()
  },
  {
    customId: "PRS-090726-004",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 446500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "CLAIM JIDAN BELANJA FITTING PVC WESTMARK TANGGAL 04/07/2026 (CLAIM HUTANG ID HUTANG HTG-013 ALOKASI DANA DARI ID BANK BNK-080726-002)",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    refHutang: "HTG-013",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T10:30:00").getTime()
  },
  {
    customId: "PRS-090726-005",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 225000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "REIMBURSE",
    description: "CLAIM JIDAN",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T11:00:00").getTime()
  },
  {
    customId: "PRS-090726-006",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 900000,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "BELANJA PROYEK",
    description: "PEMBAYARAN BAKTERI 10 BOTOL",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    referenceId: "PKM KEBON JERUK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T11:30:00").getTime()
  },
  {
    customId: "PRS-090726-007",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 20000,
    paymentMethod: "CASH",
    personalHolder: "FAISAL MUSTOPA",
    category: "OPERASIONAL",
    description: "ISI BENSIN FAISAL AMBIL DOKUMEN DI STASIUN PORIS",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-080726-002",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T14:00:00").getTime()
  },
  {
    customId: "BNK-090726-001",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 950000,
    paymentMethod: "TRANSFER",
    personalHolder: "JIDAN RAMADHAN",
    category: "BIAYA JASA",
    description: "SEDOT TINJA PUSKESMAS KEBON JERUK",
    sumberDana: "REKENING PT",
    referenceId: "PKM KEBON JERUK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T15:00:00").getTime()
  },
  {
    customId: "BNK-090726-002",
    date: "2026-07-09",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2850000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "FEE",
    description: "FEE PAK MASWAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-09T16:00:00").getTime()
  },
  {
    customId: "BNK-100726-001",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 3000000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "PATTYCASH",
    description: "TOP UP PATTYCASH KEBUTUHAN KANTOR DAN PROYEK",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T08:30:00").getTime()
  },
  {
    customId: "PRS-100726-001",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 902500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "KASBON",
    description: "KASBON TIM WELI 300, IKA 300, PANJUL 300",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-100726-001",
    referenceId: "WESTMARK",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T09:30:00").getTime()
  },
  {
    customId: "PRS-100726-002",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_PERSONAL_SPEND",
    amount: 1717500,
    paymentMethod: "CASH",
    personalHolder: "JIDAN RAMADHAN",
    category: "REIMBURSE",
    description: "CLAIM JIDAN SERVIS MOTOR DAN PULSA LISTRIK KANTOR 100K",
    sumberDana: "REKENING PT",
    refIdBank: "BNK-100726-001",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T10:30:00").getTime()
  },
  {
    customId: "BNK-100726-002",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 2500000,
    paymentMethod: "TRANSFER",
    personalHolder: "FAISAL MUSTOPA",
    category: "GAJI",
    description: "GAJI FINANCE + DENDA TELAT PAJAK 1 BULAN 500",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T11:00:00").getTime()
  },
  {
    customId: "INC-100726-001",
    date: "2026-07-10",
    type: "IN",
    flowType: "IN",
    amount: 25000000,
    paymentMethod: "TRANSFER",
    category: "TERMIN",
    description: "TRMIN MASUK DP PROYEK SUMMERSET PARSIAL 1",
    sumberDana: "REKENING PT",
    referenceId: "SUMMERSET",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T14:30:00").getTime()
  },
  {
    customId: "BNK-100726-003",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 20000000,
    paymentMethod: "TRANSFER",
    personalHolder: "MUHAMMAD YASIN",
    category: "HUTANG",
    description: "PENGEMBALIAN DANA PINJAMAN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T15:30:00").getTime()
  },
  {
    customId: "BNK-100726-004",
    date: "2026-07-10",
    type: "OUT",
    flowType: "OUT_BANK_DIRECT",
    amount: 1500000,
    paymentMethod: "TRANSFER",
    personalHolder: "AGUNG NURIMAN",
    category: "GAJI",
    description: "SISA GAJI AGUNG NURIMAN SEBELUM RESIGN",
    sumberDana: "REKENING PT",
    referenceId: "",
    recordedBy: "admin",
    timestamp: new Date("2026-07-10T16:30:00").getTime()
  }
 ];
module.exports = financialRecords;
