import type { CatalogItem } from './EKatalog';

const RAW_PRESETS = [
  // Page 1: 1. MASTER DATABASE EQUIPMENT
  { 
    i: 'md-eq-01', 
    n: 'Tangki Septictank MJ Series 1000', 
    s: 'TNK-BIO-MJ1000', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'BIO MJ', 
    pi: 3000000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Volume: 1000 Liter, Sistem anaerob biofilter.', 
    m: 'FRP (Fiberglass)', 
    cp: '1000 Liter', 
    dm: 'D.1000 mm x T.1350 mm', 
    src: 'PKM Kebon Jeruk' 
  },
  { 
    i: 'md-eq-02', 
    n: 'Bio Septic Tank 2 m³', 
    s: 'TNK-BIO-ST2M3', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'BIO MJ', 
    pi: 3500000, 
    ps: 500000, 
    pi2: 1200000, 
    u: 'Unit', 
    d: 'Tangki bio biofilter standar + filter media.', 
    m: 'FRP', 
    cp: '2 m³', 
    dm: 'D.1200 mm x T.1800 mm', 
    src: 'PT Sarana Budi' 
  },
  { 
    i: 'md-eq-03', 
    n: 'Pompa Transfer To IPAL Hs2.4S', 
    s: 'POM-TSU-HS24S', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Tsurumi', 
    pi: 5000000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Power 0.37 Kw, 1 Phase, 220V, 50Hz, Kapasitas 200 Lpm.', 
    m: 'Cast Iron, Urethane', 
    cp: '200 L/Min', 
    p: '0.37 Kw', 
    src: 'PKM Kebon Jeruk' 
  },
  { 
    i: 'md-eq-04', 
    n: 'Tangki Reaktor FRP 20 m³', 
    s: 'TNK-FRP-REACTOR-20', 
    c: 'fabrikasi tanki', 
    sc: 'FRP Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 160000000, 
    ps: 5000000, 
    pi2: 10000000, 
    u: 'Unit', 
    d: 'Dimensi: D.2.30m x P.5m x T.2.50m. Bejana reaktor biologis anaerob-aerob.', 
    m: 'FRP Composite', 
    cp: '20 m³', 
    dm: 'D.2.30 m x P.5.0 m x T.2.50 m', 
    src: 'Filter Softener' 
  },
  { 
    i: 'md-eq-05', 
    n: 'Tangki Suplay PE 3000 Liter', 
    s: 'TNK-PE-SUPLAY-3000', 
    c: 'fabrikasi tanki', 
    sc: 'Polyethylene Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 6000000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Dimensi: D.1440mm x T.2110mm. Penampung air suplai utama.', 
    m: 'Polyethylene', 
    cp: '3000 Liter', 
    dm: 'D.1440 mm x T.2110 mm', 
    src: 'Filter Softener' 
  },
  { 
    i: 'md-eq-06', 
    n: 'Tanki STP Silinder Horizontal 25 m³', 
    s: 'TNK-STP-FRP-25', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 100000000, 
    ps: 3000000, 
    pi2: 8000000, 
    u: 'Unit', 
    d: 'Material Fiber (FRP), Pipa In-Out 4 Inchi robust.', 
    m: 'FRP Composite', 
    cp: '25 m³', 
    dm: 'D.2500 mm x P.5100 mm', 
    src: 'Regulasi 2025' 
  },
  { 
    i: 'md-eq-07', 
    n: 'Centrifugal Pump Yamamax 0.37 Kw', 
    s: 'POM-CENT-YAMA-370', 
    c: 'pompa', 
    sc: 'Centrifugal Pump', 
    t: 'barang', 
    b: 'Yamamax', 
    pi: 1500000, 
    ps: 200000, 
    pi2: 500000, 
    u: 'Unit', 
    d: 'Daya 0,37Kw / 1 Phase / 220 V / 50 Hz.', 
    m: 'Cast Iron Body', 
    cp: '120 L/min max', 
    p: '0.37 Kw 220V', 
    src: 'Regulasi 2025' 
  },
  { 
    i: 'md-eq-08', 
    n: 'Pompa Filter Sirkulasi STP', 
    s: 'POM-FLT-SIRK-MED', 
    c: 'pompa', 
    sc: 'Centrifugal Pump', 
    t: 'barang', 
    b: 'Shimge / Equiv', 
    pi: 8000000, 
    ps: 500000, 
    pi2: 1200000, 
    u: 'Unit', 
    d: 'Pompa sirkulasi media filter pasir/karbon.', 
    m: 'Cast Iron', 
    cp: '100 Lpm range', 
    src: 'Regulasi 2025' 
  },
  { 
    i: 'md-eq-09', 
    n: 'Tangki STP Cylinder Horizontal 5 m³', 
    s: 'TNK-STP-CYL-FR5M', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 24500000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Unit', 
    d: 'P.350 x D.140 cm, aerob-anaerob, Mat: FRP filter.', 
    m: 'FRP Composite', 
    cp: '5 M³/Day', 
    dm: 'P.350 x D.140 cm', 
    src: 'Paket STP 5 m³' 
  },
  { 
    i: 'md-eq-10', 
    n: 'Treated Water Tank FRP 5 m³', 
    s: 'TNK-TRW-FRP-5M', 
    c: 'fabrikasi tanki', 
    sc: 'FRP Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 10000000, 
    ps: 800000, 
    pi2: 1500000, 
    u: 'Unit', 
    d: 'Diameter P.200 x L.150 x T.150 cm, Mat: FRP tank air.', 
    m: 'FRP', 
    cp: '5 m³', 
    dm: 'P.200 x L.150 x T.150 cm', 
    src: 'Paket STP 5 m³' 
  },
  { 
    i: 'md-eq-11', 
    n: 'Air Blower Yasunaga LW-150', 
    s: 'BLW-YASUNAGA-LW150', 
    c: 'blower', 
    sc: 'Diaphragm Blower', 
    t: 'barang', 
    b: 'Yasunaga', 
    pi: 9500000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Power 155 Watt, Low noise, 150 L/Min.', 
    cp: '150 L/Min', 
    p: '155 Watt 220V', 
    src: 'Paket STP 5 m³' 
  },
  { 
    i: 'md-eq-12', 
    n: 'Pompa Filter Centrifugal Ebara 65x50 FSA', 
    s: 'POM-FSA-EBARA-6550', 
    c: 'pompa', 
    sc: 'Centrifugal Pump', 
    t: 'barang', 
    b: 'Ebara', 
    pi: 14500000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Unit', 
    d: 'Head: 30 m, Power 3.7 kW, 380 V, 3 Phase flow rate.', 
    m: 'Cast Iron G20, Shaft SS403', 
    cp: '16 m³/jam', 
    p: '3.7 kW 3-Phase', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-13', 
    n: 'Sand Filter FRP Tank 16 m³/jam', 
    s: 'FLT-SAND-FRP-16MC', 
    c: 'piping', 
    sc: 'Sand Filter', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 15000000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Unit', 
    d: 'Max Press 4-6 Bar, Mat: FRP, Media Sand silika.', 
    m: 'FRP liner, PE', 
    cp: '16 m³/jam', 
    dm: 'D.400 mm x T.1650 mm', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-14', 
    n: 'Carbon Filter FRP (Item 1) 16 m³/jam', 
    s: 'FLT-CARB-FRP-16MC', 
    c: 'piping', 
    sc: 'Carbon Filter', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 6916250, 
    ps: 1000000, 
    pi2: 1500000, 
    u: 'Unit', 
    d: 'Max Press 4-6 Bar, Mat: FRP, Media Karbon adsorpsi.', 
    m: 'FRP Polyethylene', 
    cp: '16 m³/jam', 
    dm: 'D.350 mm x T.1500 mm', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-15', 
    n: 'Carbon Filter Saringan Aktif (Item 2)', 
    s: 'FLT-CARB-ACT-LT2', 
    c: 'piping', 
    sc: 'Carbon Filter', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 6916250, 
    ps: 1000000, 
    pi2: 1500000, 
    u: 'Unit', 
    d: 'Max Press 2 Bar, Mat: FRP, Media Karbon Aktif pemurni.', 
    m: 'FRP', 
    cp: '16 m³/jam', 
    dm: 'D.350 mm x T.1400 mm', 
    src: 'Lampiran Akhir' 
  },
  { 
    i: 'md-eq-16', 
    n: 'Effluent Pump Submersible Ebara 0.75kW', 
    s: 'POM-SUB-EBARA-EF8', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Ebara', 
    pi: 9000000, 
    ps: 800000, 
    pi2: 1500000, 
    u: 'Unit', 
    d: 'Head: 6m, Semi Vortex, Cast Iron casing robust, 0.75 kW.', 
    m: 'Cast Iron body', 
    cp: '0.24 m³/menit', 
    p: '0.75 kW 380V', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-17', 
    n: 'Intake Pump Submersible Ebara 0.75kW', 
    s: 'POM-SUB-EBARA-INT8', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Ebara', 
    pi: 9000000, 
    ps: 800000, 
    pi2: 1500000, 
    u: 'Unit', 
    d: 'Head: 6m, Semi Vortex, Cast Iron, 0.75 kW.', 
    m: 'Cast Iron', 
    cp: '0.24 m³/menit', 
    p: '0.75 kW', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-18', 
    n: 'RAS Pump 2 Submersible Ebara 0.4kW', 
    s: 'POM-SUB-EBARA-RAS4', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Ebara', 
    pi: 7500000, 
    ps: 600000, 
    pi2: 1200000, 
    u: 'Unit', 
    d: 'Head: 6m, Return active sludge, Cast Iron, 0.4 kW.', 
    m: 'Cast Iron', 
    cp: '0.24 m³/menit', 
    p: '0.4 kW 220V', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-19', 
    n: 'Root Blower Heavy Longtech 15 kW', 
    s: 'BLW-LONG-ROOT', 
    c: 'blower', 
    sc: 'Root Blower', 
    t: 'barang', 
    b: 'Longtech / Setara', 
    pi: 35000000, 
    ps: 3000000, 
    pi2: 5000000, 
    u: 'Unit', 
    d: 'Power 15 Kw / 380V / 3 Phase. Aerasi debit tinggi.', 
    m: 'FC200 Cast Iron', 
    cp: '16.97 m³/menit', 
    p: '15 Kw 3-Phase', 
    src: 'Spesifikasi IPAL' 
  },
  { 
    i: 'md-eq-20', 
    n: 'Tangki STP Paket Fabrikasi 10 M³/Day', 
    s: 'TNK-FAB-STP-PK10', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 205800000, 
    ps: 10000000, 
    pi2: 15000000, 
    u: 'Lot', 
    d: 'Dimensi P.420 x D.140 cm (approx). Lengkap sekat aerob-anaerob.', 
    m: 'FRP Double layer', 
    cp: '10 M³/Day', 
    dm: 'P.420 x D.140 cm', 
    src: 'STP 10 M3' 
  },
  { 
    i: 'md-eq-21', 
    n: 'Tangki STP Pasang FRP 10 m³ BIO MJ', 
    s: 'TNK-MJ-STP-10M3', 
    c: 'fabrikasi tanki', 
    sc: 'FRP Tank', 
    t: 'barang', 
    b: 'BIO MJ', 
    pi: 35000000, 
    ps: 2000000, 
    pi2: 5000000, 
    u: 'Set', 
    d: 'Dimensi D.1750 x P.2400 mm, Mat: FRP fiberglass.', 
    m: 'FRP', 
    cp: '10 m³', 
    dm: 'D.1750 x P.2400 mm', 
    src: 'ME STP 10 M3' 
  },
  { 
    i: 'md-eq-22', 
    n: 'Tangki STP Pasang FRP 15 m³ BIO MJ', 
    s: 'TNK-MJ-STP-15M3', 
    c: 'fabrikasi tanki', 
    sc: 'FRP Tank', 
    t: 'barang', 
    b: 'BIO MJ', 
    pi: 52500000, 
    ps: 3000000, 
    pi2: 7500000, 
    u: 'Set', 
    d: 'Dimensi D.1750 x P.6500 mm, Mat: FRP rib fiberglass.', 
    m: 'FRP tebal', 
    cp: '15 m³', 
    dm: 'D.1750 x P.6500 mm', 
    src: 'ME STP 15 M3' 
  },
  { 
    i: 'md-eq-23', 
    n: 'Pompa Submersible Tsurumi 10.4 Kw', 
    s: 'POM-SUB-TSUR-10KW', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Tsurumi / Equal', 
    pi: 22000000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Unit', 
    d: 'Head 12m, Power 10.4 Kw sewage flow.', 
    m: 'Cast Iron body', 
    cp: '12.000 L/jam', 
    p: '10.4 kW 3-Phase', 
    src: 'ME STP 15 M3' 
  },
  { 
    i: 'md-eq-24', 
    n: 'Tangki STP Paket Big Fabrikasi 35 M³/Day', 
    s: 'TNK-FAB-STP-PK35', 
    c: 'fabrikasi tanki', 
    sc: 'Bio Septic Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 402500000, 
    ps: 20000000, 
    pi2: 35000000, 
    u: 'Lot', 
    d: 'Dimensi P.750 x D.250 cm murni robust.', 
    m: 'FRP 10-12mm', 
    cp: '35 M³/Day', 
    dm: 'P.750 x D.250 cm', 
    src: 'STP 35 M3' 
  },
  { 
    i: 'md-eq-25', 
    n: 'Tanki STP Biofilter FRP 20 m³', 
    s: 'TNK-STP-BF-20M3', 
    c: 'fabrikasi tanki', 
    sc: 'FRP Tank', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 75000000, 
    ps: 4500000, 
    pi2: 9000000, 
    u: 'Lot', 
    d: 'Dimensi D.2000 x P.6500, Tebal 8mm, FRP.', 
    m: 'FRP 8mm', 
    cp: '20 m³', 
    dm: 'D.2000 mm x P.6500 mm', 
    src: 'WTP Boyolali' 
  },
  { 
    i: 'md-eq-26', 
    n: 'Pompa Sump Pit Tsurumi HS 2.4', 
    s: 'POM-SUMP-TSU-HS24', 
    c: 'pompa', 
    sc: 'Submersible Pump', 
    t: 'barang', 
    b: 'Tsurumi HS 2.4', 
    pi: 5500000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Power 0.4 kW, 220V, Head 12m kuras lumpur.', 
    m: 'Cast Iron & Rubber', 
    cp: '12 m³/jam', 
    p: '0.4 kW', 
    src: 'WTP Boyolali' 
  },
  { 
    i: 'md-eq-27', 
    n: 'Air Blower Diaphoragma RESUN 230W', 
    s: 'BLW-RESUN-230W', 
    c: 'blower', 
    sc: 'Diaphragm Blower', 
    t: 'barang', 
    b: 'RESUN', 
    pi: 2500000, 
    ps: 300000, 
    pi2: 600000, 
    u: 'Unit', 
    d: 'Power 230 Watt, magnetik diaphragm solid.', 
    m: 'Cast Metal', 
    p: '230 Watt 220V', 
    src: 'WTP Boyolali' 
  },
  { 
    i: 'md-eq-28', 
    n: 'Media Biofilter Sarang Tawon PVC', 
    s: 'MED-SARANG-TAWON', 
    c: 'mechanical', 
    sc: 'MBBR Media', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 5000000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Lot', 
    d: 'Material PVC honeycomb pembiakan bakteri.', 
    m: 'PVC', 
    cp: 'High Surface Area', 
    src: 'Lampiran Struktur' 
  },

  // Page 3: 2. MASTER DATABASE PIPING & VALVE
  { 
    i: 'md-pip-01', 
    n: 'Jalur pipa inlet ke septictank 4 Inchi', 
    s: 'PIP-RUP-IN4L7', 
    c: 'piping', 
    sc: 'Piping', 
    t: 'jasa', 
    b: 'Rucika', 
    pi: 5000000, 
    ps: 4500000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Rucika, Galian Jalur pipa & perapihan (Max 70m).', 
    m: 'PVC AW Rucika', 
    dm: 'DN100 (4 Inch)', 
    warranty: '1 Tahun' 
  },
  { 
    i: 'md-pip-02', 
    n: 'Instalasi Pipa sirkulasi 4 Inchi (PVC AW)', 
    s: 'PIP-RUP-SIR42', 
    c: 'piping', 
    sc: 'Piping', 
    t: 'jasa', 
    b: 'Rucika', 
    pi: 1650000, 
    ps: 1500000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Rucika, Maksimal bentang 20 m.', 
    m: 'PVC AW Rucika', 
    dm: 'DN100 (4 Inch)' 
  },
  { 
    i: 'md-pip-03', 
    n: 'Instalasi pemipaan pompa 2 Inchi (PVC AW)', 
    s: 'PIP-RUP-POM23', 
    c: 'piping', 
    sc: 'Piping', 
    t: 'jasa', 
    b: 'Rucika', 
    pi: 2000000, 
    ps: 1500000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Rucika, Maksimal bentang 30 m.', 
    m: 'PVC AW', 
    dm: 'DN50 (2 Inch)' 
  },
  { 
    i: 'md-pip-04', 
    n: 'Gate Valve Kuningan/Ancor 2 Inchi', 
    s: 'VAL-ANC-GT2', 
    c: 'piping', 
    sc: 'Valve', 
    t: 'barang', 
    b: 'Kuningan / Ancor', 
    pi: 1200000, 
    ps: 150000, 
    pi2: 250000, 
    u: 'Pcs', 
    d: 'Tipe Screw / Flange standard fitting kran pemutus.', 
    m: 'Kuningan', 
    dm: '2 Inch DN50' 
  },
  { 
    i: 'md-pip-05', 
    n: 'Check Check Valve Kuningan 2 Inchi', 
    s: 'VAL-KUN-CK2', 
    c: 'piping', 
    sc: 'Valve', 
    t: 'barang', 
    b: 'Kuningan', 
    pi: 950000, 
    ps: 100000, 
    pi2: 150000, 
    u: 'Pcs', 
    d: 'Sistem penahan balik air swing/lift check valve.', 
    m: 'Kuningan', 
    dm: '2 Inch DN50' 
  },
  { 
    i: 'md-pip-06', 
    n: 'Paket Sambungan Pipa & Aksesoris Fitting', 
    s: 'PIP-AKSESORIS-FIT', 
    c: 'piping', 
    sc: 'Piping', 
    t: 'barang', 
    b: 'Kitz / Rucika / Spindo', 
    pi: 11770000, 
    ps: 1500000, 
    pi2: 2500000, 
    u: 'Lot', 
    d: 'Valve Kitz, Pipa Rucika, Galv Spindo/Bakrie komplit.' 
  },

  // Page 3 & 4: 3. MASTER DATABASE ELECTRICAL & INSTRUMENT
  { 
    i: 'md-el-01', 
    n: 'Panel Kontrol Pompa Transfer weatherproof', 
    s: 'PNL-TRANS-BIO-MJ', 
    c: 'panel listrik', 
    sc: 'Panel Starter', 
    t: 'barang', 
    b: 'Lokal Bio MJ', 
    pi: 2000000, 
    ps: 200000, 
    pi2: 500000, 
    u: 'Is', 
    d: 'Tipe Outdoor weatherproof IP54 single automatic starter.' 
  },
  { 
    i: 'md-el-02', 
    n: 'Water Meter / Flow Meter Analog', 
    s: 'EQP-FLW-ITR-AN2', 
    c: 'electrical', 
    sc: 'Flowmeter', 
    t: 'barang', 
    b: 'BR Amico / Setara', 
    pi: 8000000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Pcs', 
    d: 'Pengukur debit mekanis analog dial duga tera kalibrasi.' 
  },
  { 
    i: 'md-el-03', 
    n: 'Panel Kontrol Utama STP', 
    s: 'PNL-STP-MAIN-SO', 
    c: 'panel listrik', 
    sc: 'Panel Kontrol Utama', 
    t: 'barang', 
    b: 'Schneider / Omron', 
    pi: 18000000, 
    ps: 1500000, 
    pi2: 3000000, 
    u: 'Unit', 
    d: 'Tipe Outdoor, Single Door panel timer alternate blower.' 
  },
  { 
    i: 'md-el-04', 
    n: 'Flow Meter Inlet Mekanis standard 2 Inchi', 
    s: 'EQP-FLW-AMI-IN2', 
    c: 'electrical', 
    sc: 'Flowmeter', 
    t: 'barang', 
    b: 'BR Amico', 
    pi: 5500000, 
    ps: 300000, 
    pi2: 700000, 
    u: 'Unit', 
    d: 'Size 2 inch, Mekanis Analog body cast iron.' 
  },
  { 
    i: 'md-el-05', 
    n: 'Instrument Control Panel (Digital/Manual)', 
    s: 'PNL-INST-DIG-MAN', 
    c: 'panel listrik', 
    sc: 'Panel Starter', 
    t: 'barang', 
    b: 'Lokal Komponen', 
    pi: 750000, 
    ps: 100000, 
    pi2: 250000, 
    u: 'Set', 
    d: 'Digital / Manual selector switch panel dosing.' 
  },
  { 
    i: 'md-el-06', 
    n: 'Panel Kontrol Utama - Outdoor standard (Schneider)', 
    s: 'PNL-CTRL-M-OUTD', 
    c: 'panel listrik', 
    sc: 'Panel Kontrol Utama', 
    t: 'barang', 
    b: 'Schneider', 
    pi: 8000000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Outdoor - Single Door Standard IP54 panel.' 
  },
  { 
    i: 'md-el-07', 
    n: 'Dosing Pump Chlorine Seko AMS200 5 Lph', 
    s: 'POM-DOS-SEKO-AMS2', 
    c: 'dosing pump', 
    sc: 'Dosing Pump', 
    t: 'barang', 
    b: 'Seko', 
    pi: 5700000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'AMS 200, 20W/230V, 5 Lph desinfektan.' 
  },
  { 
    i: 'md-el-08', 
    n: 'Coarse Bubble Diffuser Plastik DN150', 
    s: 'DIF-COARSE-DN150', 
    c: 'diffuser', 
    sc: 'Coarse Bubble Diffuser', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 150000, 
    ps: 20000, 
    pi2: 50000, 
    u: 'Lot', 
    d: 'Cap: 150 L/Min, Dia: 150 mm (6 Inch) ABS.' 
  },
  { 
    i: 'md-el-09', 
    n: 'Fine Bubble Diffuser DN250', 
    s: 'DIF-FINE-DN250', 
    c: 'diffuser', 
    sc: 'Fine Bubble Diffuser', 
    t: 'barang', 
    b: 'Garda Inovasi Globaltech', 
    pi: 250000, 
    ps: 25000, 
    pi2: 75000, 
    u: 'Lot', 
    d: 'EPDM membrane, Cap: 142 L/Min, Dia: 250 mm (10 Inch).' 
  },
  { 
    i: 'md-el-10', 
    n: 'Water Meter Effluent 12 Inchi flange', 
    s: 'EQP-WM-EFF-DN300', 
    c: 'electrical', 
    sc: 'Flowmeter', 
    t: 'barang', 
    b: 'SWM Air Limbah', 
    pi: 12500000, 
    ps: 1000000, 
    pi2: 2000000, 
    u: 'Unit', 
    d: 'Size: 12 inchi, Type: Analog flanged cast iron.' 
  },
  { 
    i: 'md-el-11', 
    n: 'Kabel Daya NYY & Kontrol Utama Supreme', 
    s: 'ELC-KABEL-SUPREME', 
    c: 'electrical', 
    sc: 'Power Cable', 
    t: 'barang', 
    b: 'Supreme / Clipsal', 
    pi: 3850000, 
    ps: 1500000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'NYY set tembaga Supreme, pelindung conduit Clipsal.' 
  },
  { 
    i: 'md-el-12', 
    n: 'Electrical Control Panel Main (Schneider)', 
    s: 'PNL-MAIN-INTEG-SC', 
    c: 'panel listrik', 
    sc: 'Panel Kontrol Utama', 
    t: 'barang', 
    b: 'Schneider / Omron', 
    pi: 5500000, 
    ps: 500000, 
    pi2: 1000000, 
    u: 'Unit', 
    d: 'Indoor panel, penunjuk Lampu led, contactor timer alternate.' 
  },

  // Page 5 & 6: 4. MASTER DATABASE PEKERJAAN (JASA & SIPIL)
  { 
    i: 'md-srv-01', 
    n: 'Biaya Tenaga Ahli Kualitas Air (Pertek)', 
    s: 'SRV-AHLI-AIR-PTK', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 15000000, 
    pi2: 0, 
    u: 'Orang', 
    d: 'Jasa kajian & penyusunan berkas Persetujuan Teknis (Pertek) kualitas air DLH.' 
  },
  { 
    i: 'md-srv-02', 
    n: 'Biaya Tenaga Ahli Lingkungan (Pertek)', 
    s: 'SRV-AHLI-LING-PTK', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 15000000, 
    pi2: 0, 
    u: 'Orang', 
    d: 'Penyusunan perhitungan beban pencemaran andal air limbah.' 
  },
  { 
    i: 'md-srv-03', 
    n: 'Tenaga Pendukung Drafter (Pertek)', 
    s: 'SRV-DRAFTER-PTK', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Desain', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 5000000, 
    pi2: 0, 
    u: 'Orang', 
    d: 'Gambar detail teknik CAD/DED (Detail Engineering Design).' 
  },
  { 
    i: 'md-srv-04', 
    n: 'Tenaga Pendukung Asisten Ahli (Pertek)', 
    s: 'SRV-ASIST-AHLI-PTK', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 4000000, 
    pi2: 0, 
    u: 'Orang', 
    d: 'Jasa asisten administrasi pemberkasan Pertek DLH.' 
  },
  { 
    i: 'md-srv-05', 
    n: 'Pengumpulan Data Primer & Sekunder', 
    s: 'SRV-DAT-PRIM-SEC', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 13000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Survei uji sampling akreditasi laboratorium KAN primer sekunder.' 
  },
  { 
    i: 'md-srv-06', 
    n: 'Penyusunan Dokumen Pertek', 
    s: 'SRV-DOKUMEN-PTK', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 4000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Penyusunan naskah kajian dokumen pertek sistem air limbah domestik.' 
  },
  { 
    i: 'md-srv-07', 
    n: 'Pembahasan Dokumen & Asistensi Dinas', 
    s: 'SRV-ASISTENSI-DIN', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 10000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Pendampingan penuh komisi dinas & sidang verifikasi DLH.' 
  },
  { 
    i: 'md-srv-08', 
    n: 'Biaya Pelaporan dan Penggandaan', 
    s: 'SRV-LAP-GANDA', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 4000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Pencetakan laporan, jilid lux, dan pengiriman berkas kajian teknis.' 
  },
  { 
    i: 'md-srv-09', 
    n: 'Penggandaan Draft Dokumen', 
    s: 'SRV-GANDA-DRAFT', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 1000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Penggandaan draft dokumen awal untuk asistensi dinas.' 
  },
  { 
    i: 'md-srv-10', 
    n: 'Penggandaan Dokumen Final', 
    s: 'SRV-GANDA-FINAL', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 1000000, 
    pi2: 0, 
    u: 'Paket', 
    d: 'Penggandaan dokumen final bertandatangan basah untuk dinas.' 
  },
  { 
    i: 'md-srv-11', 
    n: 'Pengadaan ATK & Biaya Operasional', 
    s: 'SRV-ATK-OPERASIONAL', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 2000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Penyediaan alat tulis kantor khusus project dan operational dinas.' 
  },
  { 
    i: 'md-srv-12', 
    n: 'Mobilisasi & Demobilisasi Alat Utama', 
    s: 'SRV-MOBDEMOB-ALAT', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 2500000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Logistik pengiriman alat kerja utama las scaffold dan komit.' 
  },
  { 
    i: 'md-srv-13', 
    n: 'Dewatering / Pengurasan Septictank air', 
    s: 'SRV-DEWATERING-SEP', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 5000000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Pengurasan air parit lumpur sumit penahan runtuh galian.' 
  },
  { 
    i: 'md-srv-14', 
    n: 'Tracking Jalur Pipa Air Limbah Existing', 
    s: 'SRV-TRACKING-PIPA', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 3000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Penelusuran jalur pipa buangan lama untuk pemetaan inlet.' 
  },
  { 
    i: 'md-srv-15', 
    n: 'Redrawing Jalur Pipa Eksisting', 
    s: 'SRV-REDRAW-PIPA', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Desain', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 7000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Gambar ulang skematik jalur pipa eksisting ke format digital CAD.' 
  },
  { 
    i: 'md-srv-16', 
    n: 'Bongkar Struktur Septictank Existing', 
    s: 'SRV-SIP-BONGKAR', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 3000000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Pekerjaan pembongkaran beton/bata septictank lama.' 
  },
  { 
    i: 'md-srv-17', 
    n: 'Pekerjaan Pondasi Dudukan Septictank', 
    s: 'SRV-SIP-POND-STP', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 10500000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Pekerjaan sipil slab beton bertulang K-250 duga tumpuan.' 
  },
  { 
    i: 'md-srv-18', 
    n: 'Galian Bak Sumpit (1.5 x 1.5 x 1.5 m)', 
    s: 'SRV-SIP-GALIAN-SUMP', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 6000000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Pekerjaan galian manual boks sumit tampungan parit.' 
  },
  { 
    i: 'md-srv-19', 
    n: 'Cor Plat Lantai Bawah Bak Sumpit', 
    s: 'SRV-SIP-COR-LBAWAH', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 585000, 
    pi2: 0, 
    u: 'm³', 
    d: 'Tebal 150mm Beton K-250 bertulang, volume 0.45 m³.' 
  },
  { 
    i: 'md-srv-20', 
    n: 'Pembesian Wiremesh M12 Lantai Bawah', 
    s: 'SRV-SIP-BESI-LBAWAH', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 1615000, 
    pi2: 0, 
    u: 'kg', 
    d: 'Besi Wiremesh M12 berat 85 kg solid.' 
  },
  { 
    i: 'md-srv-21', 
    n: 'Pembesian Sloop Besi M10', 
    s: 'SRV-SIP-SLOOP-M10', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 540000, 
    pi2: 0, 
    u: 'kg', 
    d: 'Besi Beton M10 berat 30 kg.' 
  },
  { 
    i: 'md-srv-22', 
    n: 'Cor Dinding Bak / Retaining Wall', 
    s: 'SRV-SIP-COR-WALL', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 2340000, 
    pi2: 0, 
    u: 'm³', 
    d: 'Beton K250 Liquid watertight, volume 1.8 m³.' 
  },
  { 
    i: 'md-srv-23', 
    n: 'Pembesian Wiremesh M12 Dinding Bak', 
    s: 'SRV-SIP-BESI-WALL', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 4845000, 
    pi2: 0, 
    u: 'kg', 
    d: 'Besi Wiremesh M12 berat 255 kg.' 
  },
  { 
    i: 'md-srv-24', 
    n: 'Bekisting Multiplek & Kaso Dinding', 
    s: 'SRV-SIP-BEKISTING-WALL', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 3500000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Pekerjaan bekisting kayu kaso multiplek cetak dinding.' 
  },
  { 
    i: 'md-srv-25', 
    n: 'Cor Plat Lantai Atas Bak Sumpit', 
    s: 'SRV-SIP-COR-LATAS', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 585000, 
    pi2: 0, 
    u: 'm³', 
    d: 'Tebal 150mm Beton K-250 bertulang, volume 0.45 m³.' 
  },
  { 
    i: 'md-srv-26', 
    n: 'Pembesian Wiremesh M12 Plat Atas', 
    s: 'SRV-SIP-BESI-LATAS', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 1615000, 
    pi2: 0, 
    u: 'kg', 
    d: 'Besi Wiremesh M12 berat 85 kg.' 
  },
  { 
    i: 'md-srv-27', 
    n: 'Bekisting Plat Atas Multiplek & Kaso', 
    s: 'SRV-SIP-BEKISTING-LATAS', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 540000, 
    pi2: 0, 
    u: 'kg', 
    d: 'Pekerjaan bekisting kayu kaso multiplek cetak plat atas.' 
  },
  { 
    i: 'md-srv-28', 
    n: 'Sipil Bak Sumpit Lengkap (2x1x1.3m)', 
    s: 'SRV-SIP-SUMP-LKP', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 15000000, 
    pi2: 0, 
    u: 'Unit', 
    d: 'Pekerjaan sipil boks sumpit lengkap waterproofing acian.' 
  },
  { 
    i: 'md-srv-29', 
    n: 'Rumah IPAL Material Baja Ringan (3x8)', 
    s: 'SRV-SIP-RMS-BAJA', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 24000000, 
    pi2: 0, 
    u: 'Unit', 
    d: 'Pekerjaan sipil pelindung shelter rumah mesin IPAL baja ringan.' 
  },
  { 
    i: 'md-srv-30', 
    n: 'Mobdemob Paket Unit STP 25 m³', 
    s: 'SRV-MOB-STP25', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 15000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Mobilisasi logistik tangki jumbo 25m3 menuju dudukan.' 
  },
  { 
    i: 'md-srv-31', 
    n: 'Asbuild Drawing & Design Proses (25m³)', 
    s: 'SRV-ASB-DRAW-25M3', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Desain', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 5400000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Penyusunan gambar terlaksanaan kelulusan verifikasi DLH.' 
  },
  { 
    i: 'md-srv-32', 
    n: 'Mobdemob Unit STP 15 m³', 
    s: 'SRV-MOB-STP15', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 15000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Mobilisasi logistik tangki jumbo 15m3 menuju dudukan.' 
  },
  { 
    i: 'md-srv-33', 
    n: 'Asbuild Drawing & Design Proses (15m³)', 
    s: 'SRV-ASB-DRAW-15M3', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Desain', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 2500000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Penyusunan gambar terlaksanaan kelulusan verifikasi DLH untuk sitem 15m3/day.' 
  },
  { 
    i: 'md-srv-34', 
    n: 'Testing Commissioning & Training Operator', 
    s: 'SRV-COMMISSIONING', 
    c: 'service maintenance', 
    sc: 'Konsultasi Pertek', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 5000000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Test-run kelaikan sistem putaran pompa blower filter.' 
  },
  { 
    i: 'md-srv-35', 
    n: 'Pekerjaan Persiapan Lahan STP Paket', 
    s: 'SRV-PREP-LAHAN', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 45650000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Land clearing, bowplank as lapangan, kupas dasar pondasi.' 
  },
  { 
    i: 'md-srv-36', 
    n: 'Instalasi Mekanikal/Elektrikal Paket STP', 
    s: 'SRV-INSTALL-ME-MAIN', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 435457000, 
    pi2: 0, 
    u: 'Is', 
    d: 'Penyambungan ME, fiting pipa, control panel, training komplit.' 
  },
  { 
    i: 'md-srv-37', 
    n: 'Mobdemob Umum Penawaran Konstruksi', 
    s: 'SRV-MOBDEMOB-UMUM', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 20350000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Logistik kontainer logistik konstruksi sediaan lapangan.' 
  },
  { 
    i: 'md-srv-38', 
    n: 'Asbuild Drawing & Design Proses Paket Big', 
    s: 'SRV-ASB-DRAW-BIG', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Desain', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 4950000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Pembuatan DED, diagram proses P&ID, dan asbuilt drawing paket sistem besar.' 
  },
  { 
    i: 'md-srv-39', 
    n: 'Pembersihan Lingkungan Pasca Konstruksi', 
    s: 'SRV-SIP-CLEANING', 
    c: 'service maintenance', 
    sc: 'Pekerjaan Sipil', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 3850000, 
    pi2: 0, 
    u: 'Lot', 
    d: 'Pekerjaan pembersihan puing galian sisa konstruksi lapangan.' 
  },
  { 
    i: 'md-srv-40', 
    n: 'Upah Pemasangan Bar Screen Stainless', 
    s: 'SRV-UPAH-BARSCREEN', 
    c: 'service maintenance', 
    sc: 'Konstruksi', 
    t: 'jasa', 
    b: 'Garda Inovasi Globaltech', 
    pi: 0, 
    ps: 165000, 
    pi2: 0, 
    u: 'Unit', 
    d: 'Pekerjaan upah instalasi sekat stainless bar saringan sampah kasar ekualisasi.' 
  }
];

export const PRESET_CATALOGS: CatalogItem[] = RAW_PRESETS.map((item, idx) => ({
  id: item.i,
  name: item.n,
  sku: item.s,
  category: item.c,
  subCategory: item.sc || 'Umum',
  type: item.t as 'barang' | 'jasa',
  brand: item.b,
  priceItem: item.pi || 0,
  priceService: item.ps || 0,
  priceInstallation: item.pi2 || 0,
  unit: item.u || 'Unit',
  description: item.d,
  specifications: `ID Ref: ${item.i}\nSKU: ${item.s}\nSumber Paket: ${item.src || 'Master GIGT'}\nSpesifikasi: ${item.d}`,
  material: item.m || 'FRP / Komposit',
  capacity: item.cp || 'N/A',
  dimensions: item.dm || 'Standar Spesifikasi',
  power: item.p || 'N/A',
  flowRate: item.cp || 'N/A',
  pressure: 'N/A',
  warranty: '1 Tahun Garansi Resmi',
  stockLocation: 'Gudang GIGT / Workshop',
  status: 'aktif',
  createdBy: 'system',
  createdByName: 'Admin Gigt',
  createdDate: '2026-06-19T10:00:00Z',
  lastUpdate: '2026-06-19T10:00:00Z',
  images: [
    item.t === 'barang'
      ? 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600'
      : 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600'
  ],
  views: 120 + idx
}));
